# frozen_string_literal: true

# Problem 002
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def find_even_fibonacci_sum_under_n(num)
  a = 1
  b = 2
  fibonacci_values = [a]

  while b < num
    fibonacci_values.append(b)
    tmp = b
    b = a + b
    a = tmp
  end
  evens = fibonacci_values.select(&:even?)
  puts evens.sum
end

find_even_fibonacci_sum_under_n(4e6) if __FILE__ == $PROGRAM_NAME
