"""
Problem 002
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def get_sum_of_even_fibonacci_under_n(n=4e6):
    a, b = 1, 2
    fibonacci_values = [a]

    while b < n:
        fibonacci_values.append(b)
        a, b = b, a + b

    even_fibonacci_values = [
        value for value in fibonacci_values if value % 2 == 0]
    return sum(even_fibonacci_values)


if __name__ == "__main__":
    answer = get_sum_of_even_fibonacci_under_n(n=4e6)
    print("Answer:", answer)
